# Generated by Django 5.1.1 on 2024-10-29 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MenPerfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pic_name', models.TextField()),
                ('picurl', models.ImageField(upload_to='perfumes/')),
                ('description', models.CharField(max_length=30)),
                ('date', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('scent', models.CharField(max_length=20)),
                ('is_for_men', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WomenPerfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pic_name', models.TextField()),
                ('picurl', models.ImageField(upload_to='perfumes/')),
                ('description', models.CharField(max_length=30)),
                ('date', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('scent', models.CharField(max_length=20)),
                ('is_for_women', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(default='pass@gmail.com', max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=30)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('is_distributor', models.BooleanField(default=False)),
                ('coupon_code', models.CharField(max_length=6)),
                ('applied_coupon', models.CharField(max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_name', models.CharField(max_length=30)),
                ('billing_address', models.CharField(max_length=30)),
                ('billing_city', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('confirmed_order_code', models.CharField(blank=True, max_length=7, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
