# Generated by Django 5.1.1 on 2024-10-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_first_name_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menperfume',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='womenperfume',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
